name: AkshravaApp
options:
  bundleIdPrefix: org.akshrava
  deploymentTarget:
    iOS: "14.0"
settings:
  SWIFT_VERSION: "5.9"
packages:
  Akshrava:
    path: ../Akshrava
targets:
  AkshravaApp:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - provision.json
          - Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.akshrava.app
      INFOPLIST_FILE: AkshravaApp/Info.plist
      TARGETED_DEVICE_FAMILY: "1"
      CURRENT_PROJECT_VERSION: 13
      MARKETING_VERSION: "0.2.13"
      GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: Akshrava
        product: Akshrava
